---
baseURL: https://josephvoss.com
languageCode: "en-us"
title: "Joseph Voss personal blog"

params:
  author:
    name: Joseph Voss
    blurb: |
      SRE at Cloudflare with a background in HPC and Mechanical Engineering 
    icons:
      - classes: fa fa-envelope fa-1x
        href: mailto:jvoss@josephvoss.com
      - classes: fab fa-github fa-1x
        href: https://github.com/josephvoss
      - classes: fab fa-linkedin fa-1x
        href: https://www.linkedin.com/in/josephvoss14
      - classes: fas fa-file-alt fa-1x
        href: /resume.pdf
  other_sites:
    - name: Photos of Luca
      url: https://luca.josephvoss.com

permalinks:
  posts: /:title/

menu:
  main:
    - name: About
      url: /about
    - name: Projects
      url: /

markup:
  goldmark:
    renderer:
      unsafe: true
