---
baseURL: ""
languageCode: "en-us"
title: "My New Hugo Site"

params:
  author:
    name: Joseph Voss
    blurb: |
      HPC Systems Engineer at Oak Ridge National Laboratory with a background in Mechanical Engineering 
    icons:
      - classes: fa fa-envelope fa-1x
        href: mailto:jvoss@josephvoss.com
      - classes: fa fa-github fa-1x
        href: https://github.com/josephvoss
      - classes: fa fa-linkedin fa-1x
        href: https://www.linkedin.com/in/josephvoss14
      - classes: fa fa-file-text fa-1x
        href: /resume.pdf

permalinks:
  posts: /:title/

menu:
  main:
    - name: About
      url: /about
    - name: Resume
      url: /resume.html
    - name: Projects
      url: /
      #    - name: Services
      #      url: /services

